#!/usr/bin/env node
/**
 * artifact:audit — build artifact content audit (M7-06, security gate 10).
 * Verifies dist/ output contains no fixture secrets and no app-owned SQLite
 * data. Integrity checksums now live in the CycloneDX SBOM (scripts/sbom.mjs);
 * when the SBOM is present, recorded hashes are re-verified here.
 */
import { createHash } from 'node:crypto';
import { readdirSync, readFileSync, existsSync, statSync } from 'node:fs';
import { join, resolve, dirname, relative } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = resolve(here, '..');

const FORBIDDEN_TEXT_PATTERNS = [
  { name: 'fixture-secret', re: /ghp_exampletokenvalue|AKIAIOSFODNN7EXAMPLE|sk-example000000000000000/ },
  { name: 'user-absolute-path', re: /C:\\Users\\|\/Users\/[a-z]+\//i },
];
const SQLITE_MAGIC = Buffer.from('SQLite format 3\0');
const FORBIDDEN_EXTENSIONS = new Set(['.db', '.sqlite', '.sqlite3', '.db-wal', '.db-shm']);

const roots = ['apps/local-agent/dist', 'apps/panel/dist'].filter((d) => existsSync(join(repoRoot, d)));
if (roots.length === 0) {
  console.error('artifact:audit: no dist output found; run npm run build first');
  process.exit(1);
}

function listFiles(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    if (statSync(p).isDirectory()) out.push(...listFiles(p));
    else out.push(p);
  }
  return out;
}

const actualHashes = new Map();
let failures = 0;
for (const root of roots) {
  for (const file of listFiles(join(repoRoot, root))) {
    const rel = relative(repoRoot, file).split('\\').join('/');
    const buf = readFileSync(file);
    const dot = rel.lastIndexOf('.');
    const ext = dot === -1 ? '' : rel.slice(dot).toLowerCase();
    if (FORBIDDEN_EXTENSIONS.has(ext)) {
      failures++;
      console.error(`FORBIDDEN app-owned database artifact: ${rel}`);
      continue;
    }
    if (buf.subarray(0, SQLITE_MAGIC.length).equals(SQLITE_MAGIC)) {
      failures++;
      console.error(`FORBIDDEN sqlite content in ${rel}`);
      continue;
    }
    const text = buf.toString('utf8');
    for (const { name, re } of FORBIDDEN_TEXT_PATTERNS) {
      if (re.test(text)) {
        failures++;
        console.error(`FORBIDDEN ${name} in ${rel}`);
      }
    }
    actualHashes.set(rel, createHash('sha256').update(buf).digest('hex'));
  }
}

// Integrity re-check against the SBOM (M7-01). The SBOM is gitignored and
// regenerated by `npm run sbom:generate`; skip when absent.
const sbomPath = join(repoRoot, 'sbom.cyclonedx.json');
let checked = 0;
if (existsSync(sbomPath)) {
  const sbom = JSON.parse(readFileSync(sbomPath, 'utf8'));
  const recorded = new Map(
    (sbom.metadata?.properties ?? [])
      .filter((p) => p.name.startsWith('aitp:artifact:sha256:'))
      .map((p) => [p.name.slice('aitp:artifact:sha256:'.length), p.value]),
  );
  for (const [rel, expected] of recorded) {
    const actual = actualHashes.get(rel);
    if (actual === undefined) {
      failures++;
      console.error(`STALE SBOM entry (artifact missing): ${rel}`);
    } else if (actual !== expected) {
      failures++;
      console.error(`HASH MISMATCH (stale SBOM, rerun sbom:generate): ${rel}`);
    } else {
      checked++;
    }
  }
  for (const rel of actualHashes.keys()) {
    if (!recorded.has(rel)) {
      failures++;
      console.error(`UNRECORDED artifact (rerun sbom:generate): ${rel}`);
    }
  }
}

if (failures > 0) {
  console.error(`artifact:audit: ${failures} violation(s)`);
  process.exit(1);
}
console.log(`artifact:audit passed (${actualHashes.size} files; ${checked} verified against SBOM)`);
